// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASVEXJ0ix3Q-QABIyTg3uM-lnlkIYcJO0',
    appId: '1:139999268733:web:0777d8b786234d034b4614',
    messagingSenderId: '139999268733',
    projectId: 'dam-u4',
    authDomain: 'dam-u4.firebaseapp.com',
    storageBucket: 'dam-u4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeBF4R9r7YE2XzLSnji2nw0f4E9cOuPr0',
    appId: '1:139999268733:android:4379f41155f98cf84b4614',
    messagingSenderId: '139999268733',
    projectId: 'dam-u4',
    storageBucket: 'dam-u4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXsYwQcBFbzh3Zo_-NsS3sbCV1FT9Ipss',
    appId: '1:139999268733:ios:c2d8efd492c1ef0a4b4614',
    messagingSenderId: '139999268733',
    projectId: 'dam-u4',
    storageBucket: 'dam-u4.appspot.com',
    iosClientId: '139999268733-hg7d27ctbn0gp7lau27k99jqm7s8335a.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU5Proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXsYwQcBFbzh3Zo_-NsS3sbCV1FT9Ipss',
    appId: '1:139999268733:ios:df9427b31070e12d4b4614',
    messagingSenderId: '139999268733',
    projectId: 'dam-u4',
    storageBucket: 'dam-u4.appspot.com',
    iosClientId: '139999268733-4tip7qhh844llsk2li7dtlelvj9qhc92.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU5Proyecto.RunnerTests',
  );
}
